set_property SRC_FILE_INFO {cfile:/home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/ip/ibert/synth/ibert.xdc rfile:../../../zubpm_hw.gen/sources_1/ip/ibert/synth/ibert.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/ip/ibert/synth/attributes.xdc rfile:../../../zubpm_hw.gen/sources_1/ip/ibert/synth/attributes.xdc id:2 order:EARLY scoped_inst:inst} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y4 [get_cells QUAD[0].u_q/CH[0].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y5 [get_cells QUAD[0].u_q/CH[1].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y6 [get_cells QUAD[0].u_q/CH[2].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y7 [get_cells QUAD[0].u_q/CH[3].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_COMMON_X0Y1 [get_cells QUAD[0].u_q/u_common/u_gthe4_common]
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y8 [get_cells QUAD[1].u_q/CH[0].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y9 [get_cells QUAD[1].u_q/CH[1].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y10 [get_cells QUAD[1].u_q/CH[2].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y11 [get_cells QUAD[1].u_q/CH[3].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_COMMON_X0Y2 [get_cells QUAD[1].u_q/u_common/u_gthe4_common]
set_property src_info {type:SCOPED_XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/TXRATE[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/RXRATE[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL0REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL0REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL0REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL1REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL1REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL1REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/CPLLREFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/CPLLREFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/CPLLREFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/TXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/TXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/RXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/RXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLL0REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLL0REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLL0REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLL1REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLL1REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLL1REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gthe4_channel/CPLLREFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gthe4_channel/CPLLREFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gthe4_channel/CPLLREFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gthe4_channel/TXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gthe4_channel/TXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gthe4_channel/RXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gthe4_channel/RXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/TXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/TXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/TXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/RXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/RXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/RXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD2[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD2[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD2[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD2[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD2[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD3[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD3[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD3[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD3[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD3[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLLRSVD2[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:594 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLLRSVD2[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:595 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLLRSVD2[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLLRSVD2[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLLRSVD2[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLLRSVD3[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLLRSVD3[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLLRSVD3[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLLRSVD3[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gthe4_common/QPLLRSVD3[4]}]
