# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.srcs/sources_1/bd/top/ip/top_smartconnect_0_0/top_smartconnect_0_0.xci
# IP: The module: 'top_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/bd_acc6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_0/bd_acc6_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_1/bd_acc6_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_2/bd_acc6_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_3/bd_acc6_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_4/bd_acc6_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_5/bd_acc6_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_6/bd_acc6_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_7/bd_acc6_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_8/bd_acc6_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_9/bd_acc6_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_10/bd_acc6_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_11/bd_acc6_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_12/bd_acc6_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_1/bd_acc6_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_1/bd_acc6_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_5/bd_acc6_s00a2s_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_6/bd_acc6_sarn_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_7/bd_acc6_srn_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_8/bd_acc6_sawn_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_9/bd_acc6_swn_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_10/bd_acc6_sbn_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_11/bd_acc6_m00s2a_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.srcs/sources_1/bd/top/ip/top_smartconnect_0_0/top_smartconnect_0_0.xci
# IP: The module: 'top_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/bd_acc6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_0/bd_acc6_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_1/bd_acc6_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_2/bd_acc6_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_3/bd_acc6_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_4/bd_acc6_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_5/bd_acc6_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_6/bd_acc6_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_7/bd_acc6_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_8/bd_acc6_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_9/bd_acc6_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_10/bd_acc6_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_11/bd_acc6_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_12/bd_acc6_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_1/bd_acc6_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_1/bd_acc6_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_5/bd_acc6_s00a2s_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_6/bd_acc6_sarn_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_7/bd_acc6_srn_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_8/bd_acc6_sawn_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_9/bd_acc6_swn_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_10/bd_acc6_sbn_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/bd_0/ip/ip_11/bd_acc6_m00s2a_0_ooc.xdc

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
