# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.srcs/sources_1/bd/top/ip/top_zynq_ultra_ps_e_0_0/top_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'top_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_zynq_ultra_ps_e_0_0/top_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_zynq_ultra_ps_e_0_0/top_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.srcs/sources_1/bd/top/ip/top_zynq_ultra_ps_e_0_0/top_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'top_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_zynq_ultra_ps_e_0_0/top_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/bouthsarath/ibert_dfe/prj/zubpm_hw/zubpm_hw.gen/sources_1/bd/top/ip/top_zynq_ultra_ps_e_0_0/top_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
